apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-ns
  name: java-deployment
  labels:
    app: java
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java
        image: java:v1
        ports:
        - containerPort: 8080

