apiVersion: v1
kind: Service
metadata:
  name: hello-app-service
  namespace: test-ns
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080 # Choose a random available port
  selector:
    app: java

